# Generated by Django 4.1.7 on 2024-03-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugues_app', '0004_alter_reservation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date_reservation',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
